- name: Test Play
  hosts: localhost
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "Hello World"

    - name: Test action plugin
      crud:
        state: present
        create:
          action: ansible.builtin.command
          args:
            _raw_params: touch test.txt
        read:
          action: ansible.builtin.command
          args:
            _raw_params: cat test.txt
        update:
          action: ansible.builtin.command
          args:
            _raw_params: touch test.txt
        delete:
          action: ansible.builtin.command
          args:
            _raw_params: rm test.txt
      register: result
    - name: Show values
      ansible.builtin.debug:
        var: result
